# Generated by Django 5.1.4 on 2025-01-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('CASE', 'Case'), ('PIECE', 'Piece')], default='PIECE', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('CASE', 'Case'), ('PIECE', 'Piece')], default='PIECE', max_length=5),
        ),
    ]
